### ISSUE TITLE
PreferenceUnion Serializer deserializes to UNKNOWN

### ISSUE THREAD

**Issue by Jon6193** [christiandeange/ozone#12]
When using the XRPCSerializerModule the getPreferences response (https://pastebin.com/ttpQJjHG) 

```
        val json = Json {
            serializersModule = XrpcSerializersModule
        }

        val preferencesResponse = json.decodeFromString<GetPreferencesResponse>(responseString)
        Log.d("TAG", "Preferences: ${preferencesResponse.preferences}")

```

The value of `preferences` will be unknown

**Comment by christiandeange** [comment]
Based on the code snippet shared, this is somewhat expected – AT Protocol uses `"$type"` as the json key for the class discriminator, instead of the default `"type"` that a kotlinx serialization Json instance will use [[documentation link]](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-builder/class-discriminator.html). If this isn't being set, it won't be able to determine which serializer should be used for union types, so they will all default to using the fallback `Unknown` type. There is a convenience method that you can use to build a Json with the appropriate configuration:

```kotlin
val json = buildXrpcJsonConfiguration(XrpcSerializersModule)
```

Alternatively you can just use `BlueskyJson` member directly, which is configured in the same manner for you [[documentation link]](https://ozone.christian.sh/ozone/sh.christian.ozone/-bluesky-json.html).

**Comment by Jon6193** [comment]
```
buildXrpcJsonConfiguration(XrpcSerializersModule)
```

Worked as expected. Thank you for the help!
